### ISSUE TITLE
Cannot rebuilt PE on Windows 10

### ISSUE THREAD

**Issue by stevielavern** [serpilliere/elfesteem#19]
Rebuilding a binary (using "str(pe)") on Windows 10 doesn't produce a valid PE file, even if no modifications have been done to the original PE (which is valid).

**Steps to reproduce:**
```
In [1]: from elfesteem import pe_init

In [2]: pe = pe_init.PE(open('C:/Windows/System32/ntdll.dll','rb').read())

In [3]: pe.SHList
Out[3]:
#  section         offset   size   addr     flags   rawsize
 0 .text          00000400 10d7a3 00001000 60000020 0010d800
 1 RT             0010dc00 0001f5 0010f000 60000020 00000200
 2 .rdata         0010de00 0442e7 00110000 40000040 00044400
 3 .data          00152200 00780c 00155000 c0000040 00004000
 4 .pdata         00156200 00da94 0015d000 40000040 0000dc00
 5 .mrdata        00163e00 0034d0 0016b000 c0000040 00003600
 6 .00cfg         00167400 000018 0016f000 40000040 00000200
 7 .rsrc          00167600 069448 00170000 40000040 00069600
 8 .reloc         001d0c00 0004b4 001da000 42000040 00000600

In [4]: f = open('test.dll', 'wb'); f.write(str(pe)); f.close()

In [5]: import ctypes

In [6]: ctypes.CDLL('test.dll')
---------------------------------------------------------------------------
WindowsError                              Traceback (most recent call last)
<ipython-input-6-f0a9a7593b4e> in <module>()
----> 1 ctypes.CDLL('test.dll')

c:\python27-x64\lib\ctypes\__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    360
    361         if handle is None:
--> 362             self._handle = _dlopen(self._name, mode)
    363         else:
    364             self._handle = handle

WindowsError: [Error 193] %1 is not a valid Win32 application
```

This also displays a message box with: 

> test.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000007b.

To be sure that the problem was not with Python/Ctypes, we can also try to load the dll using rundll32:

```
C:\> rundll32.exe C:\Windows\System32\ntdll.dll,atoi
# Works fine, no error displayed

C:\> rundll32.exe test.dll,atoi
# Message box: "There was a problem starting test.dll. test.dll is not a valid Win32 application"
``` 

**Version info:**
- Windows 10 x64 Version 1703 (OS Build 15063.674)
- Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
- elfesteem (installed from git, branch master, last commit #32aeb419)

**Comment by serpilliere** [comment]
Hi!

I have installed a Windows 10 x64 1703 (10.0.15063.540), get the ntdll using explorer, rebuild it on a linux box using this script:
```python
import sys

from elfesteem import pe
from elfesteem.pe_init import PE

in_pe = PE(open(sys.argv[1]).read())

print repr(in_pe.SHList)

open('out.bin', 'w').write(str(in_pe))
```

and launched rundll32 stuff: ~~Everything seems ok :sweat:~~
So I reproduced the problem

**Comment by serpilliere** [comment]
Hi

The bug is solved on my setup using the branch `fix_align` : https://github.com/serpilliere/elfesteem/tree/fix_align
Can you try it and tell me if it's ok for you?
If it's ok, I am merging it to master

**Comment by stevielavern** [comment]
Tried it today and the problem seems to be fixed.
Thanks a lot for your quick answer !

**Comment by stevielavern** [comment]
However, there still seems to be another problem, for instance when trying to rebuild KernelBase.dll without modifying anything:

```
In [1]: p = 'C:/Windows/System32/KernelBase.dll'

In [2]: from elfesteem import pe_init

In [3]: pe = pe_init.PE(open(p,'rb').read())

In [4]: f = open('test.dll', 'wb'); f.write(str(pe)); f.close()

In [5]: import ctypes

In [6]: ctypes.CDLL('test.dll')
---------------------------------------------------------------------------
WindowsError                              Traceback (most recent call last)
<ipython-input-6-f0a9a7593b4e> in <module>()
----> 1 ctypes.CDLL('test.dll')

c:\python27-x64\lib\ctypes\__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    360
    361         if handle is None:
--> 362             self._handle = _dlopen(self._name, mode)
    363         else:
    364             self._handle = handle

WindowsError: [Error 1114] A dynamic link library (DLL) initialization routine failed

In [7]: ctypes.CDLL(p)
Out[7]: <CDLL 'C:/Windows/System32/KernelBase.dll', handle 1d9a0000 at d4a9748>
```

EDIT: sorry I looked too quickly at the error message and thought it was the same as before. This rather seems like an initialization issue within the DLL itself, and is maybe not related to elfesteem re-building. I'll investigate the issue by debugging the DllEntryPoint.

**Comment by serpilliere** [comment]
Yes: I tried to loadlibrary the original `KernelBase.dll`, it seems to return a null handle (even if I rename the dll)

**Comment by serpilliere** [comment]
PR Merged
