### ISSUE TITLE
Deadlock with bigger ELF executable

### ISSUE THREAD

**Issue by philicious** [serpilliere/elfesteem#2]
`e = elf_init.ELF(open(FILENAME, 'rb').read())` results in hanging script, eating up more and more RAM. When you stop it, it tells you it was here
https://github.com/serpilliere/elfesteem/blob/master/elfesteem/strpatchwork.py#L27

With `dd if=App of=App.trunc bs=1024 count=39405` I found out that the last "good" size was 40350720Bytes (count=39405) and 40351744 resulting in deadlock. 

I couldnt tell what the root cause is as I'm not familiar with the codebase but it certainly has to do with memory and boundaries.

Btw. I also tried https://bitbucket.org/LouisG/elfesteem which also comes with ELF64 in general. Same results with that bigger file.

I hope you have an idea what could be the problem ?

**Comment by serpilliere** [comment]
Is it possible to have your truncated binary which triggers the problem?

**Comment by philicious** [comment]
@serpilliere so my test file would be https://mega.nz/#!PtRlFCBB!UvIiGxV7DnxnEsiLVXi81iuI-ZvaNMzHoRNa1u8R6Vc (not truncated). 

Also have a look at https://bitbucket.org/LouisG/elfesteem/issues/3/deadlock-with-bigger-elf-executable
as LouisG already has a patch https://bitbucket.org/LouisG/elfesteem/commits/268990b4c41f30257b9654fc8d0b75d939e27b4b

it increases performance.

I timed it. Simply reading in the ELF + printing entry:

8,08s user 0,28s system 99% cpu 8,391 total // that 39MB file which wasnt working at all before

1,66s user 0,14s system 81% cpu 2,230 total // another 37MB file which was working before.

So there still is quite a gap of 7secs but only 2MB more. So I guess there is more to fix/enhance but for me the 8secs are acceptable

**Comment by serpilliere** [comment]
The PR #3 should resolve the issue. It takes around 5 seconds on the non truncated binary here.
Can you confirm the PR fixes your issue?

**Comment by philicious** [comment]
I can confirm its working now with #3 :+1:

**Comment by serpilliere** [comment]
Ok, can I close the issue?

**Comment by philicious** [comment]
sure :)
