### ISSUE TITLE
Some change of API were not needed

### ISSUE THREAD

**Issue by LRGH** [serpilliere/elfesteem#4]
It is not true that  `__setitem__ in python 32bit is limited to [0-0x7fffffff]`.
The problem is because you did not use "New Style Classes".
Instead of the complicated commits of November 2nd and December 13th, you could simply have replaced `class virt:` by `class virt(object):` and everyhing would have been OK.

**Comment by serpilliere** [comment]
Hi!

Thanks for the tips. After a little check, it seems that `__getslice__` has no limits, only the `__len__` must return an int.

I think I will re enable the old API because it was so convenient.

**Comment by LRGH** [comment]
Yes. The replacement of `__len_` by `max_addr` is unavoidable.
I would also recomment to apply https://bitbucket.org/LouisG/elfesteem/commits/7a399b6caa320564e35dd220523b9ba5b154a7e8
But I am not sure: I don't have any binary that would need your modification of `getsectionbyrva`.

**Comment by serpilliere** [comment]
Hi!

the PR #7 may fix this issue.

**Comment by serpilliere** [comment]
The API is now merged
