### ISSUE TITLE
pe_init produces bad resource directories

### ISSUE THREAD

**Issue by philicious** [serpilliere/elfesteem#5]
I tried with two exes. One complexer one with icons, dialog etc and one that only has version info. Both produce a bad exe when read in and written out.

```
from elfesteem import *

FILENAME = "symget.exe"
e = pe_init.PE(open(FILENAME, 'rb').read())
open(FILENAME + "_copy", "wb").write(str(e))
```

symget.exe is from Microsoft and public available.

**Comment by LRGH** [comment]
I think that patch https://github.com/serpilliere/elfesteem/commit/17a8c68580396ebb7cd1c9af69c098e962fbe687 is the culprit.

**Comment by philicious** [comment]
@serpilliere I can confirm @LRGH

**Comment by serpilliere** [comment]
Thanks for the feedback!
I think I have found the culprit. I rebuild the `repr` of a python object in the binary... which is bad.

The PR #6 fixes this issue. I try with `symget.exe` it works.
Are you ok with this?

**Comment by philicious** [comment]
@serpilliere yes. I can confirm #6 fixes it. Tested with an exe that has Dialogs, Icons, Configuration Files etc in ResourceDir

**Comment by serpilliere** [comment]
Merged!
